---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  {{ if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{ end }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.backend.name }}
        image: 522986700920.dkr.ecr.eu-west-1.amazonaws.com/cineindex-app:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-config
        - secretRef: 
            name: cineindex-secret
        resources:
          limits:
            memory: {{ .Values.app.backend.resources.limits.memory }}
            cpu: {{ .Values.app.backend.resources.limits.cpu }}
          requests:
            memory: {{ .Values.app.backend.resources.requests.memory }}
            cpu: {{ .Values.app.backend.resources.requests.cpu }}
        ports:
        - containerPort: 8080
      - name: {{ .Values.app.frontend.name }}
        image: 522986700920.dkr.ecr.eu-west-1.amazonaws.com/cineindex-proxy:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: {{ .Values.app.frontend.resources.limits.memory }}
            cpu: {{ .Values.app.frontend.resources.limits.cpu }}
          requests:
            memory: {{ .Values.app.frontend.resources.requests.memory }}
            cpu: {{ .Values.app.frontend.resources.requests.cpu }}
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: {{ .Values.app.frontend.volumeMounts.mountPath }}
            name: {{ .Values.app.frontend.volumeMounts.name }}
            subPath: nginx.conf
            readOnly: true
      volumes:
        - name: {{ .Values.app.frontend.volumeMounts.name }}
          configMap:
            name: {{ .Release.Name }}-proxyconfig
            items:
              - key: nginx.conf
                path: nginx.conf     